Fixes #208
rakugoteam/Rakugo-Dialogue-System pull request #211
Opened 2023-04-24 15:27 UTC by Jeremi360

fixes #208

2023-04-29 14:56 UTC, theludovyc requested changes

2023-04-29 14:56 UTC, theludovyc commented on addons/Rakugo/lib/systems/Parser.gd
> +	NUMERIC = "-?[1-9][0-9\\.]*",
With this regex, you can't write a number like "0.5". But you can write "1.1.1"

2023-04-29 14:56 UTC, theludovyc commented on addons/Rakugo/lib/systems/Parser.gd
> +	TOKEN_NUMERIC = "-?[1-9][0-9\\.]*",
If you are agree, we can remove all tokens :)

2023-04-30 07:44 UTC, Jeremi360 commented on addons/Rakugo/lib/systems/Parser.gd
> +	NUMERIC = "-?[1-9][0-9\\.]*",
Strange I sure that I change it to 1 to 0, maybe I pressed ctrl-z by mistake before commit or something.
I will fix it soon

2023-04-30 07:47 UTC, Jeremi360 commented on addons/Rakugo/lib/systems/Parser.gd
> +	TOKEN_NUMERIC = "-?[1-9][0-9\\.]*",
If we really don't use it then, I will remove them, but in speared PR / issue to keep things clean

2023-05-01 13:14 UTC, Jeremi360 commented on addons/Rakugo/lib/systems/Parser.gd
> +	NUMERIC = "-?[1-9][0-9\\.]*",
fixed with my last commit.
Yes I tested my new regex you can check it here: https://regexr.com/7d0d4 @theludovyc

2023-05-04 18:21 UTC, theludovyc commented on addons/Rakugo/lib/systems/Parser.gd
> +	TOKEN_NUMERIC = "-?[1-9][0-9\\.]*",
I am agree with you :) !

2023-05-04 18:22 UTC, theludovyc commented on addons/Rakugo/lib/systems/Parser.gd
> +	NUMERIC = "-?[1-9][0-9\\.]*",
This link with some test is so perfect 👌 !

2023-05-04 18:22 UTC, theludovyc approved these changes

2023-05-04 18:22 UTC, theludovyc commented
Ready for merge :) !

2023-05-04 19:00 UTC, merged