Fix#273
rakugoteam/Rakugo-Dialogue-System pull request #274
Opened 2024-06-23 07:19 UTC by Jeremi360

- Fixes #273
- Fixes/add some comments
- Removes Rakugo.tscn as we don't use it any more in 2.x

2024-06-23 10:09 UTC, theludovyc requested changes

2024-06-23 10:09 UTC, theludovyc commented on Test/TestExecuter/fix_273/Fix273.gd
Hello,

This is not a GUT test

2024-06-23 11:21 UTC, Mojken commented on addons/Rakugo/Rakugo.gd
This is a very big diff for a very small change in logic. Consider separating the codestyle changes into a separate PR.

2024-06-23 11:25 UTC, Mojken commented on Test/TestExecuter/fix_273/fix273.rk
Consider simplifying this test further by removing the character, making var be a global variable instead

2024-06-23 11:41 UTC, Jeremi360 commented on addons/Rakugo/Rakugo.gd
My bad, I'm leazy, and want to fix bugs asap,
so often when I have other small changes (like comments, removing some old stuff),
I don't bother myself with spliting it into separed PRs.
I know I should.

2024-06-23 11:44 UTC, Jeremi360 commented on Test/TestExecuter/fix_273/fix273.rk
You are right, I added character to be sure it wasn't some character raltead bug.
Now as I'm making this test in to proper GUT(Godot Unit Test), I will simplelfy it.

2024-06-25 12:08 UTC, Jeremi360 commented on Test/TestExecuter/fix_273/Fix273.gd
I made it into GUT (last commit), but GUT framework is broken,
as it crashes due some, bad code with singnals:
 
![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/8d64e5f0-435f-4a82-a662-1fef199febbe)

2024-06-25 12:24 UTC, Jeremi360 commented on Test/TestExecuter/fix_273/Fix273.gd
I made it into GUT script, but GUT can't find/run this script :/
I don't know way as it is in `Test/TestExecuter/` which is in our GUT confing.

![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/3d1fbbf9-b15b-4c86-9bda-8d085b6fb6fb)

2024-06-26 07:51 UTC, Jeremi360 commented on Test/TestExecuter/fix_273/Fix273.gd
Now it is and it is passed:
![image](https://github.com/rakugoteam/Rakugo-Dialogue-System/assets/1294815/c425553f-e879-4bee-b675-358d8c1981a2)

2024-06-26 10:02 UTC, theludovyc approved these changes

2024-06-26 10:05 UTC, theludovyc commented
Hello @Mojken ,

Welcome and thank you for the review :blush:

2024-06-27 07:40 UTC, merged